"use client";
import {useEffect,useState} from "react";
declare global{interface Window{FB?:{init:(o:Record<string,unknown>)=>void;login:(cb:(r:any)=>void,o?:Record<string,unknown>)=>void};fbAsyncInit?:()=>void}}
const CONFIG_ID=process.env.NEXT_PUBLIC_META_CONFIG_ID||"1095242176288378";
export default function MetaConnect({locale}:{locale:string}){
 const ar=locale==="ar",appId=process.env.NEXT_PUBLIC_META_APP_ID;
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[connected,setConnected]=useState(false),[assets,setAssets]=useState<any[]>([]),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 const refresh=async()=>{try{const r=await fetch("/api/meta/connection",{cache:"no-store"}),d=await r.json();if(d.ok){setConnected(!!d.connected);setAssets(d.assets||[])}}catch{}};
 useEffect(()=>{void refresh()},[]);
 useEffect(()=>{if(!appId)return;const init=()=>{if(!window.FB)return;window.FB.init({appId,cookie:true,xfbml:false,version:"v24.0"});setReady(true)};window.fbAsyncInit=init;if(window.FB){init();return}if(!document.getElementById("facebook-jssdk")){const s=document.createElement("script");s.id="facebook-jssdk";s.async=true;s.defer=true;s.crossOrigin="anonymous";s.src="https://connect.facebook.net/en_US/sdk.js";s.onerror=()=>setErr(ar?"تعذر تحميل Meta SDK.":"Meta SDK could not be loaded.");document.body.appendChild(s)}},[appId,ar]);
 const save=async(token:string,expiresIn?:number)=>{try{const r=await fetch("/api/meta/connection",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accessToken:token,expiresIn})}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Connection failed");setConnected(true);setAssets(d.assets||[]);setMsg(ar?"تم ربط Meta وحفظ الاتصال بأمان.":"Meta connected and stored securely.")}catch(e){setErr(e instanceof Error?e.message:"Connection failed")}finally{setBusy(false)}};
 const connect=()=>{setErr("");setMsg("");if(!appId||!ready||!window.FB){setErr(ar?"Meta SDK غير جاهز.":"Meta SDK is not ready.");return}setBusy(true);try{window.FB.login((r:any)=>{const t=r.authResponse?.accessToken;if(!t){setBusy(false);setErr(ar?"لم يكتمل تسجيل الدخول.":"Meta login did not complete.");return}void save(t,r.authResponse?.expiresIn)},{config_id:CONFIG_ID})}catch(e){setBusy(false);setErr(e instanceof Error?e.message:"Meta login failed")}};
 const disconnect=async()=>{setBusy(true);setErr("");setMsg("");try{const r=await fetch("/api/meta/disconnect",{method:"POST"}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Disconnect failed");setConnected(false);setAssets([]);setMsg(ar?"تم فصل Meta وحذف بيانات الاتصال.":"Meta disconnected and stored connection removed.")}catch(e){setErr(e instanceof Error?e.message:"Disconnect failed")}finally{setBusy(false)}};
 return <div className="mt-10 rounded-[2rem] border bg-white p-6 shadow-sm"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><div className="text-xs font-black uppercase tracking-[0.2em] text-metrix-700">{ar?"تكاملات المنصات":"PLATFORM INTEGRATIONS"}</div><h2 className="mt-2 text-2xl font-black">{ar?"ربط Meta":"Connect Meta"}</h2><p className="mt-2 text-sm text-zinc-500">{connected?(ar?"Meta متصل بـ metriX.":"Meta is connected to metriX."):(ar?"اربط Facebook Pages وInstagram Professional.":"Connect Facebook Pages and Instagram Professional.")}</p><div className="mt-2 text-xs text-zinc-400">Meta configuration: <span className="font-mono">{CONFIG_ID}</span></div></div>{connected?<button onClick={disconnect} disabled={busy} className="rounded-full border border-red-200 px-6 py-3 font-black text-red-700 disabled:opacity-50">{busy?"...":(ar?"فصل Meta":"Disconnect Meta")}</button>:<button onClick={connect} disabled={busy||!ready} className="rounded-full bg-metrix-900 px-6 py-3 font-black text-white disabled:opacity-50">{busy?"...":(ar?"ربط Meta":"Connect Meta")}</button>}</div>{connected&&<div className="mt-5 rounded-2xl bg-emerald-50 p-4"><div className="font-black text-emerald-900">{ar?"متصل":"Connected"} ✓</div><div className="mt-3 grid gap-2 md:grid-cols-2">{assets.map(a=><div key={a.asset_type+":"+a.external_id} className="rounded-xl bg-white p-3 text-sm"><div className="text-xs font-bold uppercase text-zinc-400">{a.asset_type==="facebook_page"?"Facebook Page":"Instagram Professional"}</div><div className="mt-1 font-black">{a.name||a.username||a.external_id}</div>{a.username&&<div className="text-zinc-500">@{a.username}</div>}</div>)}</div></div>}{msg&&<div className="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{msg}</div>}{err&&<div className="mt-4 rounded-2xl bg-red-50 p-4 text-sm font-semibold text-red-700">{err}</div>}</div>
}
