import "server-only";

export type BrightMention = { platform:string; external_id:string; author_name:string|null; author_username:string|null; content:string; post_url:string|null; published_at:string; likes:number; shares:number; replies:number; views:number };
const API="https://api.brightdata.com/datasets/v3/scrape";
const DATASETS={ facebook:"gd_lkaxegm826bjpoo9m5", linkedin:"gd_lyy3tktm25m4avu764", googleMaps:"gd_luzfs1dn2oa0teb81" };
function s(...v:any[]){for(const x of v){if(typeof x==="string"&&x.trim())return x.trim();if(typeof x==="number")return String(x)}return ""}
function n(...v:any[]){for(const x of v){if(x===0)return 0;if(x!==undefined&&x!==null&&x!==""){const z=Number(String(x).replace(/,/g,""));if(Number.isFinite(z))return z}}return 0}
function iso(v:any){if(!v)return new Date().toISOString();if(typeof v==="number"||/^\d+$/.test(String(v))){const x=Number(v);const d=new Date(x>100000000000?x:x*1000);if(!Number.isNaN(d.getTime()))return d.toISOString()}const d=new Date(v);return Number.isNaN(d.getTime())?new Date().toISOString():d.toISOString()}
async function scrape(dataset:string,input:any[],query:Record<string,string>={}){const token=process.env.BRIGHTDATA_API_TOKEN;if(!token)throw new Error("BRIGHTDATA_API_TOKEN is missing");const u=new URL(API);u.searchParams.set("dataset_id",dataset);u.searchParams.set("include_errors","true");u.searchParams.set("format","json");for(const[k,v]of Object.entries(query))u.searchParams.set(k,v);const r=await fetch(u.toString(),{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({input}),cache:"no-store"});const t=await r.text();let j:any;try{j=JSON.parse(t)}catch{throw new Error(`Bright Data returned non-JSON (${r.status})`)}if(!r.ok)throw new Error(s(j?.message,j?.error,`Bright Data ${r.status}`));return Array.isArray(j)?j:Array.isArray(j?.data)?j.data:[]}
function fbUrl(v:string){v=String(v||"").trim();if(/^https?:\/\//i.test(v))return v;return `https://www.facebook.com/${v.replace(/^@/,"").replace(/^facebook\.com\//i,"")}`}
function liUrl(v:string){v=String(v||"").trim();if(/^https?:\/\//i.test(v))return v;v=v.replace(/^@/,"").replace(/^linkedin\.com\//i,"");return v.startsWith("company/")||v.startsWith("in/")?`https://www.linkedin.com/${v}`:`https://www.linkedin.com/company/${v}`}
export async function collectFacebook(target:string){const rows=await scrape(DATASETS.facebook,[{url:fbUrl(target)}]);return{externalId:null,mentions:rows.filter((x:any)=>x&&!x.error).map((x:any)=>({platform:"Facebook",external_id:`fb:${s(x.post_id,x.shortcode,x.id,x.url)}`,author_name:s(x.page_name,x.user_name,x.user_username_raw,x.profile_handle)||null,author_username:s(x.profile_handle,x.user_username_raw)||null,content:s(x.content,x.text,x.description)||"[Facebook post]",post_url:s(x.url)||null,published_at:iso(x.date_posted,x.created_at,x.timestamp),likes:n(x.likes,x.num_likes_type?.num),shares:n(x.num_shares,x.shares),replies:n(x.num_comments,x.comments),views:n(x.video_view_count,x.play_count,x.views)})) as BrightMention[]}}
export async function collectLinkedIn(target:string){const url=liUrl(target);const isProfile=/linkedin\.com\/in\//i.test(url);const rows=await scrape(DATASETS.linkedin,[{url,only_authored_posts:true}],{type:"discover_new",discover_by:isProfile?"profile_url":"company_url"});return{externalId:null,mentions:rows.filter((x:any)=>x&&!x.error).map((x:any)=>({platform:"LinkedIn",external_id:`li:${s(x.id,x.post_id,x.activity_id,x.url)}`,author_name:s(x.user_name,x.author_name,x.name,x.headline)||null,author_username:s(x.user_url,x.use_url,x.author_url)||null,content:s(x.post_text,x.text,x.description,x.title,x.headline)||"[LinkedIn post]",post_url:s(x.url)||null,published_at:iso(x.date_posted,x.published_at,x.timestamp),likes:n(x.num_likes,x.likes),shares:n(x.num_reposts,x.num_shares,x.shares),replies:n(x.num_comments,x.comments),views:n(x.views,x.impressions)})) as BrightMention[]}}
export async function collectGoogleMapsReviews(target:string){const url=String(target||"").trim();if(!/^https?:\/\//i.test(url))throw new Error("Google Maps requires a full public place URL");const rows=await scrape(DATASETS.googleMaps,[{url,days_limit:90,sort_by:"Newest"}]);return{externalId:null,mentions:rows.filter((x:any)=>x&&!x.error).map((x:any)=>{const rating=n(x.rating,x.review_rating,x.stars);const text=s(x.review_text,x.text,x.review,x.comment)||(rating?`${rating}/5 Google Maps rating`:"[Google Maps review]");return{platform:"Google Maps",external_id:`gm:${s(x.review_id,x.id,`${x.reviewer_name||"reviewer"}:${x.timestamp||x.review_date||""}`)}`,author_name:s(x.reviewer_name,x.author_name,x.name)||null,author_username:s(x.reviewer_url,x.author_url)||null,content:rating?`[Rating: ${rating}/5] ${text}`:text,post_url:s(x.url,x.review_url)||url,published_at:iso(x.review_date,x.date,x.timestamp,x.date_posted),likes:n(x.review_likes,x.likes),shares:0,replies:x.owner_answer?1:n(x.replies),views:0}}) as BrightMention[]}}
